CREATE TABLE HOTEL(
ID NUMBER,
CONSTRAINT ID_PK PRIMARY KEY (ID),
COUNTRY NVARCHAR2(50) DEFAULT 'N/A',
CONSTRAINT CHECK (COUNTRY != 'Romania' AND COUNTRY != 'Belgium' AND COUNTRY != 'China' AND  COUNTRY != 'Ukraine'),
CITY NVARCHAR2(50) NOT NULL,
STREET NVARCHAR2(50)
);